### ISSUE TITLE
Bug on Glob evaluating GLOB_BRACE

### ISSUE THREAD

**Issue by thomasvargiu** [laminas/laminas-stdlib#15]
Working on #11 I noticed a probably bug on `Glob` class. Seems that `GLOB_BRACE` is always enabled.

This because conditionals use wrong precedence with the not ` !` operator, that it's applied to `$flags` first.

https://github.com/laminas/laminas-stdlib/blob/f0b299de11700203c4a9644c97aa869613743f4b/src/Glob.php#L114-L116

https://github.com/laminas/laminas-stdlib/blob/f0b299de11700203c4a9644c97aa869613743f4b/src/Glob.php#L200

**Comment by Ocramius** [comment]
Handled in #43
