### ISSUE TITLE
ArrayUtils::iteratorToArray() different behaviour when recursive is false

### ISSUE THREAD

**Issue by thomasvargiu** [laminas/laminas-stdlib#18]
`ArrayUtils::iteratorToArray()` has a different behaviour when `$iterator` is a `Traversable` object with a `toArray()` method.

When `$recursive === false` the method returns the result of its iterator, but when ` $recursive === true` it returns the result of its `toArray()` method.

For a next major release I would suggest to make the method simplier without to handle objects with `toArray()` methods.
Another solution could be to return the `toArray()` even when `$recursive === false`.

https://github.com/laminas/laminas-stdlib/blob/f0b299de11700203c4a9644c97aa869613743f4b/src/ArrayUtils.php#L233-L247

**Comment by Ocramius** [comment]
Looks like a clear bug to me :+1: 

 > For a next major release I would suggest to make the method simplier without to handle objects with `toArray()` methods.

Totally agree: restricting inputs will help a lot here. We can most certainly design a separate utility that works with iterators, if needed.

**Comment by garygitton** [comment]
@thomasvargiu Do you have an example of an object that I could try ?

**Comment by Ocramius** [comment]
Handled in #42
