### ISSUE TITLE
PHP 8.1: PHP Deprecated:  The Serializable interface is deprecated.

### ISSUE THREAD

**Issue by matbech** [laminas/laminas-stdlib#24]
There are some PHP Deprecated warnings with PHP 8.1:
```
PHP Deprecated:  The Serializable interface is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in vendor\laminas\laminas-stdlib\src\SplPriorityQueue.php on line 23

PHP Deprecated:  The Serializable interface is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in vendor\laminas\laminas-stdlib\src\ArrayObject.php on line 39
```

More details for the change in PHP 8.1:
https://github.com/php/php-src/blob/php-8.1.0alpha1/UPGRADING#L295

**Comment by Ocramius** [comment]
Beware: this library declares PHP ~8.0.0 compatibility, not ^8.0.0

**Comment by matbech** [comment]
The new methods were introduced in PHP 7.4:
https://wiki.php.net/rfc/phase_out_serializable
There is no good reason to use the broken Serializable interface.

**Comment by Ocramius** [comment]
Removal of an interface is a BC break, so we'll likely need a new major
release to get rid of them.

**Comment by matbech** [comment]
It might be enough to implement __serialize() and __unserialize() as the PHP doc is suggesting.

**Comment by bradymiller** [comment]
Just need to support both mechanisms to avoid BC breaks:
https://php.watch/versions/8.1/serializable-deprecated
(then can remove Serializable interface in future when php 7.3 is a distant memory)

**Comment by Ocramius** [comment]
The BC break has nothing to do with the supported PHP version: an interface
removal is a BC break for consumers.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/
