### ISSUE TITLE
Composer require laminas/laminas-zendframework-bridge is unnecessary

### ISSUE THREAD

**Issue by vaclavvanik** [laminas/laminas-stdlib#28]
### Feature Request

I think this package is stand-alone and does not need dependency on laminas/laminas-zendframework-bridge.

**Comment by Ocramius** [comment]
It's required until the next major release, since it provides compatibility
for folks still using `zendframework/zend-stdlib`.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by michalbundyra** [comment]
Bridge has been removed in release 3.5.0 - for reference please see: https://github.com/laminas/laminas-stdlib/pull/33
