### ISSUE TITLE
PHP 8.1: Incompatibility with `IteratorAggregate::getIterator`

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-stdlib#31]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | latest

#### Summary

`ArrayObject` and `PriorityQueue` have incompatibilities with `IteratorAggregate::getIterator`

```
PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught Return type of ArrayObject::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

#### Current behavior

Tests are failing

#### How to reproduce

Run tests with PHP 8.1

#### Expected behavior

Tests are passing

**Comment by tobias-trozowski** [comment]
solved by https://github.com/laminas/laminas-stdlib/pull/35

**Comment by Ocramius** [comment]
Thanks @tobias-trozowski!
