### ISSUE TITLE
BC break in 3.6.3 with sorting paths

### ISSUE THREAD

**Issue by snapshotpl** [laminas/laminas-stdlib#45]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 3.6.3

#### Summary

#43 with fix for #15 introduces BC break. #17 explained it already.

#### Previous behavior

File paths didn't sort.

#### Current behavior

File paths are sort now.

**Comment by snapshotpl** [comment]
I have use `Glob::glob` in `laminas-modulemanager` context in `config_glob_paths`

**Comment by Ocramius** [comment]
Should we just revert?

**Comment by snapshotpl** [comment]
Not sure.

For me call `fallbackGlob` with `$forceFallback` and skip `systemGlob` should help.

https://github.com/laminas/laminas-stdlib/blob/3.7.x/src/Glob.php#L55

**Comment by driehle** [comment]
I can confirm this bug. Updating from laminas-stdlib 3.6.2 to 3.6.3 breaks my application. I am having a configuration file named `ldap.global.php` which seems not to be loaded anymore and then a service breaks, throwing an exception for missing its configuration.

Thanks, snapshotpl, for figuring out the cause!

By the way, I am using pretty much the default Laminas MVC skeleton with the following configuration in `application.config.php`:

```
        'config_glob_paths' => [
            realpath(__DIR__) . '/autoload/{{,*.}global,{,*.}local}.php',
        ],
```

... and the following in `development.config.php(.dist)`:

```
        'config_glob_paths' => [
            realpath(__DIR__) . '/autoload/{,*.}{global,local}-development.php',
        ],
```

This is how the merged configuration looks like:

![grafik](https://user-images.githubusercontent.com/1586788/147602602-7e95da4f-f61b-498c-90ee-c96cb22f1e37.png)

So far everything fine, I think, but `ldap.global.php` is only loaded with laminas-stdlib 3.6.2, not with 3.6.3.

**Comment by snapshotpl** [comment]
Looks like this will break most laminas app, so need to revert ASAP. @Ocramius ? @weierophinney ?

**Comment by Ocramius** [comment]
Send a revert patch 👍

**Comment by naur1970** [comment]
It seems to be negation sign is forgotten here https://github.com/laminas/laminas-stdlib/blob/3.7.x/src/Glob.php#L112
if (! $flags & self::GLOB_BRACE) {  was before 
if (self::flagsIsEqualTo($flags, self::GLOB_BRACE)) { is now

**Comment by driehle** [comment]
I can confirm that adding the missing negation sign fixes the broken loading of configuration files in my MVC application.

**Comment by Ocramius** [comment]
@driehle should I wait for your work on the patch, or revert?

**Comment by driehle** [comment]
@Ocramius I think a revert is not needed. Simply fixing the negation sign should be fine. What I am currently trying to to is setting up a CI job that runs with Alpine Linux, so that we have a failing test case. 

I think that the current issue only appears on Alpine Linux, which doesn't provide GLOB_BRACE. At least my app runs on Alpine Linux. Maybe @snapshotpl and @naur1970 can confirm that for him the issue appears on Alpine Linux as well? Anyways, currently CI runs on Ubuntu (latest) only, which provides GLOB_BRACE. Hence, the fallback is never actually covered in CI which is likely why this error has not been discovered prior to merging.

**Comment by naur1970** [comment]
Confirm! In my case the ploblem has manifested on Alpine Linux.

**Comment by driehle** [comment]
@Ocramius I think I got it all solved, see #46 for a patch.

**Comment by snapshotpl** [comment]
Yes, it appears on Alpine. Thanks for patch!

**Comment by snapshotpl** [comment]
FIxed in #46

**Comment by weierophinney** [comment]
Ah, that's interesting! Previously, the only OS that didn't provide GLOB_BRACE was IBM i - and we had workarounds for that (it's why we even had the functionality in here!).

Will look at the patch later today - thanks for doing the legwork!

**Comment by driehle** [comment]
Thanks to @naur1970, who found the actual cause!

**Comment by Ocramius** [comment]
Thanks for getting it released so quickly, y'all: stellar work! :muscle:

**Comment by nynka** [comment]
Good job guys! I was struggling with this for a while today. Thanks for fixing so quickly! 👍
