### ISSUE TITLE
PHP 8.1 Deprecation notice for Laminas\Stdlib\ArrayStack::getIterator()

### ISSUE THREAD

**Issue by alexgit2k** [laminas/laminas-stdlib#50]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.8.x (master)

#### Summary

With PHP 8.1 Laminas\Stdlib\ArrayStack::getIterator() shows a deprecation notice.

#### Current behavior

`Deprecated: Return type of Laminas\Stdlib\ArrayStack::getIterator() should either be compatible with ArrayObject::getIterator(): Iterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in src/ArrayStack.php on line 25`

#### How to reproduce

`php -e src/ArrayStack.php`

#### Expected behavior

No deprecation notice

**Comment by Ocramius** [comment]
@alexgit2k send a patch to `3.8.x` and it shall be fixed :+1:

**Comment by Ocramius** [comment]
Actually, probably for `3.7.x`, since it is a patch for `3.7.1`

**Comment by Ocramius** [comment]
Handled in #54
