### ISSUE TITLE
`PriorityQueue` generics do not align with `SplPriorityQueue`

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-stdlib#71]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.12.0

#### Summary

In one of the older releases, generics were added for the `PriorityQueue`.
I've updated to that and also got psalm bitching about `SplPriorityQueue`.
Now, since I want to fix both issues, I have to adapt different styles.

#### Current behavior

Generics for `PriorityQueue` needs to be written like:

`PriorityQueue<TValue,TPriority>`

Generics for `SplPriorityQueue` needs to be written like:
`SplPriorityQueue<TPriority,TValue>`

The latter feels more convenient, as its also aligned with arrays and keys. Since the priority queue is some kind of "array" as well, thats more inconvenient if I have to annotate the value as the key and the key as a value within the generic annotation in `PriorityQueue` implemetation.

#### How to reproduce

```php
use Laminas\Stdlib\PriorityQueue;
use SplPriorityQueue;

final class Foo
{
    /** @var PriorityQueue<non-empty-string,int> */
    public PriorityQueue $laminas;
   
    /** @var PriorityQueue<int, non-empty-string> */
    public SplPriorityQueue $php;


    public function addString(): void
    {
        $this->php->insert('foo', count($this->php->count());
        $this->laminas->insert('foo', count($this->laminas->count());
    }
}
```

#### Expected behavior

```php
use Laminas\Stdlib\PriorityQueue;
use SplPriorityQueue;

final class Foo
{
    /** @var PriorityQueue<int, non-empty-string> */
    public PriorityQueue $laminas;
   
    /** @var PriorityQueue<int, non-empty-string> */
    public SplPriorityQueue $php;


    public function addString(): void
    {
        $this->php->insert('foo', count($this->php->count());
        $this->laminas->insert('foo', count($this->laminas->count());
    }
}
```

**Comment by gsteel** [comment]
This was my fault 😬 - Does #72 look good to you @boesing

**Comment by Ocramius** [comment]
Discussed in #72 - we will keep the "broken" generics order, to avoid introducing an intentional BC break in the type definition.

Annoying, but not a major issue, so we keep them in the current order, and just improved naming to reduce confusion.
