### ISSUE TITLE
Mocking ParametersInterface leads to Deprecation messages

### ISSUE THREAD

**Issue by mimmi20** [laminas/laminas-stdlib#85]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.17.0

#### Summary

When Mocking the ParametersInterface, the following Deprecation message is created:

```shell
Mock_ParametersInterface_a1ece25f implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)
```

#### Current behavior

The deprecation message is created.

#### How to reproduce

run the following test

```php
<?php

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\MockObject\Exception;

class RequestTest extends TestCase
{
    /** @throws Exception */
    public function testGetQuery(): void
    {
        $query = $this->createMock(\Laminas\Stdlib\ParametersInterface::class);
        $query->expects(static::never())
            ->method('get');

        $request = new \Laminas\Http\Request();
        $request->setQuery($query);

        self::assertSame($query, $request->getQuery());
    }
}

```

#### Expected behavior

no Deprecation message.

**Comment by Ocramius** [comment]
We can't just drop an interface without massive BC implications anyway: has to stay for the foreseeable future.

A deprecation warning here is better than a hard downstream system crash.

**Comment by mimmi20** [comment]
Could this be implemented in version 4?

**Comment by Ocramius** [comment]
Most likely, but for just a deprecation issue, it isn't worth pursuing a new major release.
