### ISSUE TITLE
mb_convert_encoding with html-entities deprecated in php 8.2

### ISSUE THREAD

**Issue by siliconalchemy** [laminas/laminas-stdlib#87]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.17.0

#### Summary
StringWrapper\Mbstring breaks in php 8.2

#### Current behavior

`Exception #0 (Exception): Deprecated Functionality: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in ...vendor/laminas/laminas-stdlib/src/StringWrapper/MbString.php on line 125`

#### How to reproduce

```
        $this->mbString->setEncoding('UTF-8', 'html-entities');
        $result = $this->mbString->convert($result);
```

#### Expected behavior

No error!

**Comment by Xerkus** [comment]
This is PHP deprecation. You will have to migrate away from using `html-entities` with mbstring.

**Comment by siliconalchemy** [comment]
But shouldn't this be fixed in StringWrapper/MbString.php?  This contains mb_convert_encoding() which is deprecated?

**Comment by Xerkus** [comment]
`mb_convert_encoding()` is not deprecated. Using it for `html-entities` is.

**Comment by siliconalchemy** [comment]
Oh duh.  Right, sorry :)
